name: Build, Test & Release

env:
  VERSION: ${{ github.sha }}

on: [ push ]

jobs:
  format_terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Environment
        run: mkdir .terraform && echo "prod" >> .terraform/environment
      - name: Terraform Init
        run: terraform init
      - name: Terraform Format
        run: terraform fmt -check -recursive
      - name: Terraform Validate
        run: terraform validate

  test_generator_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x ./generator/gradlew
    - name: Run tests
      run: cd generator && ./gradlew clean test

  push_generator_image:
    runs-on: ubuntu-latest
    needs: [format_terraform, test_generator_app]
    environment: prod
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: generator
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Package and push Docker Image
        run: ./gradlew build dockerPush
        
  push_proxy_image:
    runs-on: ubuntu-latest
    needs: [format_terraform, test_generator_app]
    environment: prod
    if: github.ref == 'refs/heads/master'	
    steps:		
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          path: ./proxy
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dgrew/tokenproxy
          tags: $VERSION
          
  deploy_terraform:
    runs-on: ubuntu-latest
    needs: [push_generator_image, push_proxy_image]
    environment: prod
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Environment
        run: mkdir .terraform && echo "prod" >> .terraform/environment
      - name: Terraform Init
        run: terraform init
      - name: Terraform Workspace
        run: terraform workspace select prod || terraform workspace new prod
      - name: Terraform Destroy
        run: terraform destroy
      - name: Terraform Apply
        run: terraform apply -auto-approve -var 'tag=$VERSION''
