name: Build, Test & Release

env:
  VERSION: ${{ github.sha }}

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x ./generator/gradlew
    - name: Run tests
      run: cd generator && ./gradlew clean test

  push_generator_image:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x ./generator/gradlew
      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Package and push Docker Image
        run: cd generator && ./gradlew build dockerPush
        
  push_proxy_image:
    runs-on: ubuntu-latest
    needs: test
    steps:		
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          path: ./proxy
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dgrew/tokenproxy
          tags: ${{ github.sha }}